### ISSUE TITLE
Help with installation and enhance to read_me

### ISSUE THREAD

**Issue by Marethyu6** [Michal-Szczepaniak/sddm-theme-amadeus#5]
Hi sir, 
I'm trying to install this theme, but I'm having some issues you might easily help me with, though I would also like to take the chance to suggest you the enhancement of the "READ_ME" file for a better understanding of the instructions. 
If you would kindly help me with my issue, I'm willing to collect the steps to go through the installation myself and then give the complete text to you to add into the repository, so that other _not-very-supah-hacka_ like me will have less troubles when installing your wonderful creation.
I think that's all, I'll wait for your answer before explain my issue, and sorry for the bad use of terminology but I'm still a newbie here... 

> El. Psy. Kongroo.

**Comment by Michal-Szczepaniak** [comment]
I even recorded video but can't post it on github. Anyway

First you need to get source, you can do it by clicking clone button and downloading zip. Then extract it to directory (preferably same name as zip's name). Then as root you need to move it to the `/usr/share/sddm/themes/` directory. You can do that by opening terminal, navigating to Downloads folder and running
`sudo mv sddm-theme-amadeus /usr/share/sddm/themes/` 
then if you are using kde plasma, open system settings, navigate to startup and shutdown, pick amadeus theme and click apply. It's really simple.

AMA

**Comment by Marethyu6** [comment]
First of all: thank you a lot for replying, I'm quite stalking all of the Steins;Gate subreddit who installed it to get a hand and it's super nice that the first reply came from you!! 
Then: my issue is related (I think) to the fact that I'm on Ubuntu with Gnome, so I've installed the sddm by just `sudo apt install sddm` and succesfully set it as default instead of the other (gdm3), I've also already followed the steps in the read_me _aka_ exactly as you wrote above. So my issue(s) were (the first, solved) and is (the second, still there) as follows
1. sddm didn't generated any sddm.conf or sddm.config.d file in my `/etc` nor in any bit of my computer and so I weren't able to switch to your theme (only had the default one) >>> after a day of trial I just ended up by creating the config file myself and now your theme is set up...
2. ...BUT I still shows the default theme for my distro with the error 
> `/usr/share/sddm/themes/sddm-theme-amadeus-master/Main.qml` 9:9 : module "QtQuick.VirtualKeyboard 2.1" not installed

I tried to understand a bit more about qml and fix it myself as for the config, but it's a lot, I only got that the QtQuick.VirtualKeyboard 2.1 is something required that you wrote in SpTextBox.qml into the components folder...

How can I fix that situation? Did I still miss something _veeery_ dumb as I suspect?

**Comment by Michal-Szczepaniak** [comment]
Yeah virtual keyboard was an issue there was separate branch iirc… yeah, try this branch https://github.com/Michal-Szczepaniak/sddm-theme-amadeus/tree/no-virtualkeyboard

**Comment by Michal-Szczepaniak** [comment]
Actually let me update it

**Comment by Michal-Szczepaniak** [comment]
That branch is older though, if you have enough skill then stay on master but revert these changes (by simply removing those lines in your files) https://github.com/Michal-Szczepaniak/sddm-theme-amadeus/commit/55bcd772c3d95a5361cca04dab64eab8bc3dea57

**Comment by Marethyu6** [comment]
I think I can do it, if it's only a matter of opening the file and erase lines,_buuut_ what's the program to modify qml in linux?

**Comment by Michal-Szczepaniak** [comment]
you can use any text editor really, even vim if you can escape it lmao

**Comment by Marethyu6** [comment]
Can I just copy the right text (without those lines) into a text editor, save it as Main.txt, then change the extension to .qml?

**Comment by Marethyu6** [comment]
Ah well I'm slow typing ahah ;D

**Comment by Michal-Szczepaniak** [comment]
sure you can

**Comment by Michal-Szczepaniak** [comment]
i mean if you are on linux then file extension doesn't matter it's not windows, just open qml file using text editor

**Comment by Michal-Szczepaniak** [comment]
qml file is simple text file

**Comment by Marethyu6** [comment]
Well, not working still, I got this error at login: 
> The current theme cannot be loaded due to the errors below, please select another theme. 
> file://usr/share/sddm/themes/sddm-theme-amadeus-master/Main.qml:70:3: Type SpTextBox unavailable
> file://usr/share/sddm/themes/sddm-theme-amadeus-master/components/SpTextBox.amp:26:1: module _[here I think the continue of the error might be cut out of the screen...]_

Just to be sure I've not screwed up the whole thing in editing that file here are the steps I made: 
1. copied the whole text of Main.qml to a new text file
2. deleted the lines you highlighted in green in the [](https://github.com/Michal-Szczepaniak/sddm-theme-amadeus/commit/55bcd772c3d95a5361cca04dab64eab8bc3dea57) 
3. saved it
4. added .qml at the end of the name by renaming the file
5. replaced the previous Main.qml in the sddm theme folder

**Comment by Marethyu6** [comment]
°of course the name of the file in the second error is SpTextBox.**qml**, sorry for that, I had to transcript to my mobile because I can't take screenshots in the login greeter screen it seems...

**Comment by Michal-Szczepaniak** [comment]
Then you lack package. Here it's named `libqt5-qtgraphicaleffects` but what you are searching for is qtgraphicaleffects

**Comment by Marethyu6** [comment]
Uhm, ok, and how do I get that package sorry? 
Because afaik (like for the qtvirtualkeyboard) those things are not something you just download and install...

**Comment by Michal-Szczepaniak** [comment]
No you just install it (qtvirtualkeyboard aswell)  you are on shitbuntu which isn't really user friendly but i think i can help
`apt install qml-module-qtquick-virtualkeyboard qml-module-qtgraphicaleffects`
this should help for both issues

**Comment by Marethyu6** [comment]
Yeah I understand, but for the moment I'll stick on it (_shit_ buntu I mean), I'm slowly trying other distros beginning with Debian (which is basically the same without the _shit_ added ). 
However, I'll try your workaround this evening then I'll go back here reporting, thank you again and again
P.S.: first I'll try doing it from the start, BUT this time having those modules install, then I just hope it's fixed... otherwise I'm just going to install Debian with kde and that would settle it for good 🖖

**Comment by Michal-Szczepaniak** [comment]
That's not workaround that's proper fix actually, editing file was workaround xd

That's really not a proper thread for it but i'll recommend considering opensuse :P

**Comment by Marethyu6** [comment]
Derp, sorry sir, not my primary language (both english and computer-terminology) :F 
[OT _aka_ I don't mind serendipity when it knocks at the door] About opensuse: I only heard about it, why that in particular?

**Comment by Marethyu6** [comment]
I tried from step 1 (Main.qml as is in your zip file)... 
Got this error:

> Current theme cannot be loaded due to errors below, please select another theme

> file:///usr/share/sddm/themes/sddm-theme-amadeus-master/Main.qml:35:3: Type InputPanel unavailable
> qrc:/QtQuick/VirtualKeyboard/content/InputPanel.qml:125:5 Type Keyboard unavailable

Should I try with the Main.qml edited as you wrote me before?

**Comment by Michal-Szczepaniak** [comment]
Yeah sure go ahead.

_english isn't my primary language either_

**Comment by Marethyu6** [comment]
Well, I tried with the modified Main.qml and... **IT JUST APPEARS NOW**!! _°I'm trying not to cry for joy :')_
THANK YOU sir, mostly for having dealt with such a noob as me and patiently followed my errors, seriously, I would like to do more to express my gratitude for both the creation of this wonderful customization and the help in installing (though I'm a poor noob in all sense so sorry no bucks to throw at ya... :face_with_head_bandage: )

One last thing (other then the opensuse explanation if you'd like to): every time I shut down the system it tells me there's another user logged in, is it ok? Also, now during power on/off black screens I can see three or two lines of code appearing at the top left corner: they're about bluetooth-stuff (which is not working in my ubuntu since installation so I don't think they're related) but started to appear after the sddm install so are they just fine? Any idea on how to get rid of those _truly_ minor issues now that the big one is done?

**Comment by Michal-Szczepaniak** [comment]
First, no need to thank me i'm not such good guy as you think (at least you can use english and have common sense compared to others)

No idea how to fix your minor idea.

opensuse needs bit of maintenence but i believe it's much much easier for beginners that buntu but noone even considers it. As beginner you can do _everything_ from gui but you can learn to do it from terminal aswell so great for learning _and again noone considers it for beginners idk why_

**Comment by Michal-Szczepaniak** [comment]
Next thing would be to modify screen lock in kde… but yeah if you would like to update readme feel free to do so in PR. I'm closing this issue
