### ISSUE TITLE
Enhancement: Display a different background on secondary screens

### ISSUE THREAD

**Issue by pmdevita** [Michal-Szczepaniak/sddm-theme-amadeus#8]
An idea I had was to display the BG image from the game used prior to the login screen on secondary monitors. This would make the theme more like conventional login screens where only the primary monitor displays the text boxes and such.

![amadeus-secondary](https://user-images.githubusercontent.com/6833157/87463454-67519480-c5df-11ea-9f30-35630764e9de.png)

I'm guessing some users would prefer the current style so we could make it configurable as well.

I'm still a bit new to SDDM and QML in general but I can try and implement it if that's OK with you.

**Comment by Michal-Szczepaniak** [comment]
i don't own second monitor but do whatcha want, it's free country, if it will be optional or something then it's all fine. Currently in SDM themes i think the login displays on all displays so it definitely should be optional (idk if my theme displays on all displays)

**Comment by catumin** [comment]
Currently yes, each monitor will show the username and password fields and
you can just pick one and type in it.

**Comment by Michal-Szczepaniak** [comment]
So if it will be optional, feel free. I'm thinking about making splash theme (it's rather simple from what've seen) with s;g splash (in reddit threads someone just played mp4 on login) so that would be cool addition. Another thing is lock screen theme which currently is not themable but i could change sources.

**Comment by pmdevita** [comment]
I was thinking about making an Amadeus splash screen as well but I wasn't able to get plymouth working. If I'm able to I can try to help with that (or if there is something else that works better than plymouth). That video is a lot better quality than the frames I extracted from the game so we should definitely use that.

What desktop environment would you implement the lock screen for?

**Comment by Michal-Szczepaniak** [comment]
@pmdevita kde obviously, and when talking about splashscreen i mean the one after login so it's not plymouth it's part of kde

**Comment by Michal-Szczepaniak** [comment]
@pmdevita https://github.com/Michal-Szczepaniak/amadeus-kde-splashscreen :) Now we are missing first part of the video that i took it from, we could make it into plymouth theme but plymouth doesn't work on my pc so can't do shit

**Comment by pmdevita** [comment]
Looks good! I can't get plymouth working either lol I dunno if I'll be able to do it

Additionally, I can't find any documentation for how to differentiate screens in sddm so I'm not sure if showing the different background on secondary monitors is even possible.

**Comment by Michal-Szczepaniak** [comment]
You might want to ask on kde irc channel but here is my idea, hide all controls and fade wallpaper to the second one if current screen isn't focused (put mousearea on background or smth)

**Comment by pmdevita** [comment]
I figured it out. https://github.com/sddm/sddm/blob/1231b5fce8b7f9d99b3a0b8fa17e10d797890c43/data/themes/maui/Main.qml#L66

There is apparently an undocumented global variable that can tell a component if it is displaying on the primary screen or not. SDDM documentation is really, really bad, especially for a QML noob like me.

Anyways, I'll be finishing the changes soon. Should the behavior be default or one you have to configure for?

**Comment by Michal-Szczepaniak** [comment]
Well my idea wasn't bad either, i think current behavior should be default

**Comment by pmdevita** [comment]
I did try your idea prior, it was very clever. This method should hopefully be more consistent though. 

I'll fix my pull request to keep current behavior default.
